---
- name: Read partition layout
  setup:
    filter: "ansible_devices"
  register: part_info

- name: Output disks
  debug:
    var: part_info.ansible_facts.ansible_devices.sda.partitions
 
- name: Read partition 
  command: "parted /dev/sda unit GB print free | grep 'Free Space' | tail -n1 | awk '{print $3}'"
  become: yes
  register: part_free_space

- name: Output disks
  debug:
    var: part_free_space
 # - name: Output disks
 #   debug:
 #     var: hostvars[inventory_hostname].ansible_devices.sda.partitions

