---
# - name: Output disks
#   debug:
#     var: ansible_facts.devices.sda

- name: Output disks
  debug:
    var: ansible_facts.ansible_devices.keys() | map('regex_search', 'sd.*') | select('string') | list

- name: Output facts
  debug:
    var: ansible_facts

- name: Read partition 
  shell: "parted /dev/sda unit GB print free | grep 'Free Space' | tail -n1 | awk '{print $3}'"
  become: yes
  register: part_free_space

# - name: Output disks
#   debug:
#     var: part_free_space.stdout

 # - name: Output disks
 #   debug:
 #     var: hostvars[inventory_hostname].ansible_devices.sda.partitions

