---
- set_fact:
    lvm_disk: "{{ ansible_facts.devices.keys() | map('regex_search', 'sd.*') | select('string') | list }}"

- set_fact:
    lvm_device_auto: "/dev/{{ lvm_disk[0] }}"

- debug:
    msg: "Disk detected: {{ lvm_device_auto }}"

# - name: Output facts
#   debug:
#     var: ansible_facts

- name: "Read partition information from {{ lvm_device_auto }}"
  shell: "parted {{ lvm_device_auto }} unit GB print free | grep 'Free Space' | tail -n1 | awk '{print $3}'"
  become: yes
  register: part_free_space

#part_free_space.stdout

- set_fact:
    part_free_space_filter: "{{ 1.25 | replace('GB', '') | int }}"

- debug:
    msg: "{{ lvm_device_auto }} has: {{ part_free_space_filter }} GB unused"
